# Generated by Django 3.2.12 on 2022-06-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_like_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_recipes',
        ),
    ]
