# Generated by Django 3.2.12 on 2022-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeprocess'),
        ('accounts', '0005_remove_user_like_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_recipes',
            field=models.ManyToManyField(related_name='like_users', to='recipes.Recipe'),
        ),
    ]
