# Generated by Django 3.2.12 on 2022-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=254)),
                ('nation', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('cooking_time', models.IntegerField()),
                ('calorie', models.IntegerField(blank=True, null=True)),
                ('qnt', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
    ]
